// using Rest Client extension for VS CODE to run commands below

get http://localhost:3000/api

### get a card by id
get http://localhost:3000/api/card/1

### get all cards
get http://localhost:3000/api/cards

### create a card
POST http://localhost:3000/api/card
Content-Type: application/json

{
    "url": "https://example.com",
    "host": "example.com",
    "ogMetaTags": {
        "title": "title",
        "description": "description",
        "image": "example.com/imageurl.jpg"
    }
}


### delete a card by ID
delete http://localhost:3000/api/card/000
